apiVersion: v2
name: aqsh
description: Async Queue for Shell Scripts with Redis backend
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - aqsh
  - async
  - queue
  - shell
  - redis
maintainers:
  - name: kube-federated-auth-aqsh
