apiVersion: v2
name: kube-federated-auth-aqsh
description: Independent Deployments — kube-federated-auth + aqsh + Redis as separate Deployments
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - kubernetes
  - authentication
  - federation
  - aqsh
  - async
  - queue
  - shell
  - redis
maintainers:
  - name: kube-federated-auth-aqsh
