apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: kube-federated-auth-reader
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
