apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kfa-config
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  clusters.yaml: |
{{ tpl (.Files.Get "files/clusters.yaml") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-aqsh-config
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  tasks.yaml: |
{{ .Files.Get "files/tasks.yaml" | indent 4 }}
---
{{- $scriptFiles := .Files.Glob "files/scripts/*" }}
{{- if $scriptFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-aqsh-scripts
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
{{- range $path, $content := $scriptFiles }}
  {{ base $path }}: |
{{ $content | toString | indent 4 }}
{{- end }}
{{- end }}
---
{{- $caCertFiles := .Files.Glob "files/ca-certs/*.crt" }}
{{- if $caCertFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kfa-ca-certs
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
{{- range $path, $content := $caCertFiles }}
  {{ base $path }}: |
{{ $content | toString | indent 4 }}
{{- end }}
{{- end }}
