{{- if .Values.reader.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.reader.serviceAccountName }}
  namespace: {{ .Values.reader.namespace }}
  labels:
    app: kube-federated-auth-reader
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end }}
