{{- $hasCerts := false }}
{{- range .Values.kubeFederatedAuth.remoteClusters }}
{{- if .caCert }}{{- $hasCerts = true }}{{- end }}
{{- end }}
{{- $hasTokens := false }}
{{- range .Values.kubeFederatedAuth.remoteClusters }}
{{- if .bootstrapToken }}{{- $hasTokens = true }}{{- end }}
{{- end }}
{{- if and .Values.kubeFederatedAuth.remoteClusters $hasCerts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kfa-certs
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{- range .Values.kubeFederatedAuth.remoteClusters }}
  {{- if .caCert }}
  {{ .name }}-ca.crt: {{ .caCert | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if and .Values.kubeFederatedAuth.remoteClusters $hasTokens }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kfa-tokens
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{- range .Values.kubeFederatedAuth.remoteClusters }}
  {{- if .bootstrapToken }}
  {{ .name }}-token: {{ .bootstrapToken | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
