{{- if .Values.kubeFederatedAuth.remoteClusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kfa-certs
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{- range .Values.kubeFederatedAuth.remoteClusters }}
  {{ .name }}-ca.crt: {{ .caCert | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kfa-tokens
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{- range .Values.kubeFederatedAuth.remoteClusters }}
  {{ .name }}-token: {{ .bootstrapToken | b64enc | quote }}
  {{- end }}
{{- end }}
