{{- if .Values.kubeFederatedAuth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kube-federated-auth
  labels:
    app: kube-federated-auth-aqsh
    component: kube-federated-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.kubeFederatedAuth.service.type }}
  ports:
  - port: {{ .Values.kubeFederatedAuth.service.port }}
    targetPort: 8443
    protocol: TCP
    name: http
  selector:
    app: kube-federated-auth-aqsh
    component: kube-federated-auth
    release: {{ .Release.Name }}
{{- end }}
{{- if .Values.aqsh.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aqsh.service.name | default (printf "%s-aqsh" .Release.Name) }}
  labels:
    app: kube-federated-auth-aqsh
    component: aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.aqsh.service.type }}
  ports:
  {{- if .Values.kubeAuthProxy.enabled }}
  - port: {{ .Values.kubeAuthProxy.port }}
    targetPort: {{ .Values.kubeAuthProxy.port }}
    protocol: TCP
    name: http-proxy
  {{- else }}
  - port: {{ .Values.aqsh.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  {{- end }}
  selector:
    app: kube-federated-auth-aqsh
    component: aqsh
    release: {{ .Release.Name }}
{{- end }}
