{{- if .Values.vaultSecrets.enabled }}
{{- range .Values.vaultSecrets.secrets }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .name }}
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
spec:
  path: {{ .path | quote }}
  type: {{ .type | default "Opaque" }}
{{- end }}
{{- end }}
