{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-aqsh
  labels:
    app: kube-federated-auth-aqsh
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  {{- with .Values.istio.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.istio.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- $hasHttp := or .Values.istio.virtualService.http .Values.istio.virtualService.autoRouteToAqsh }}
  {{- if $hasHttp }}
  http:
  {{- with .Values.istio.virtualService.http }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.istio.virtualService.autoRouteToAqsh }}
    {{- $aqshSvcName := .Values.aqsh.service.name | default (printf "%s-aqsh" .Release.Name) }}
    {{- $port := .Values.kubeAuthProxy.port }}
    {{- if not .Values.kubeAuthProxy.enabled }}
      {{- $port = .Values.aqsh.service.port }}
    {{- end }}
    - route:
      - destination:
          host: {{ $aqshSvcName }}
          port:
            number: {{ $port }}
  {{- end }}
  {{- end }}
{{- end }}
