apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kube-federated-auth
  labels:
    app: kube-federated-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: kube-federated-auth
    release: {{ .Release.Name }}
